version: '3.9'

services:
  newsboard:
    build:
      context: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py crontab add && 
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=anything
      - DEBUG=1
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=newsdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
