version: '3.9'

services:
  newsapp:
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./appnew:/newsApp
    environment:
      - SECRET_KEY=anything
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=apidb
      - DB_USER=devuser
      - DB_PASS=123456
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=apidb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=123456
