# Generated by Django 4.0.1 on 2022-01-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_upvotes_post_upvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commenter',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='author_name',
            field=models.CharField(max_length=50),
        ),
    ]
