# Generated by Django 4.0.1 on 2022-01-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_upvote_voter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upvote',
            name='voter',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='upvote',
            unique_together={('voter', 'post')},
        ),
    ]
